"""LangGraph state-graph orchestration: smart routing -> query decomposition -> self-correcting retrieval -> generation -> hallucination check.

Graph structure (conditional edges marked with *):
    START -> plan -> retrieve -> grade -*-> generate -> verify -*-> END
                        ^           |            ^          |
                        |           v            +----------+ (loop back in strict mode when not grounded)
                        +------- rewrite

Nodes push custom events (dict) via get_stream_writer, which rag.stream_answer converts to SSE:
  {"type":"routing","kbs":[...]}   routing result (plan node)
  {"type":"retrieving"}            retrieval started
  {"type":"stage","stage":"grading|rewriting|verifying|regenerating"}  extended stages
  {"type":"generating"}            generation started
  {"type":"token","delta":"..."}   incremental answer text
  {"type":"restart"}               verification failed, regenerating; frontend should clear the current answer buffer

When no LLM key is configured, plan/grade/verify pass through and behavior degrades to the original "retrieve + summarize" pipeline.
"""
from __future__ import annotations

import json
import logging
import re
from typing import TypedDict

from langgraph.config import get_stream_writer
from langgraph.graph import END, START, StateGraph

from app.services import es_client, llm
from app.services.embedding import embed_text

logger = logging.getLogger("rag.graph")

MAX_REWRITES = 2   # max query-rewrite retries
MAX_GENERATES = 2  # max generations (including hallucination-check loop-backs)


class RagState(TypedDict, total=False):
    original_query: str        # user's original question
    kb_ids: list[int]          # candidate knowledge bases after permission filtering
    kb_catalog: list[dict]     # candidate KB metadata [{id,name,description}]
    history: list[dict]        # conversation history
    routed_kb_ids: list[int]   # target knowledge bases after routing
    routed_kbs: list[dict]     # routing result for display [{id,name}]
    sub_queries: list[str]     # retrieval sub-queries (multi-hop decomposition / replaced after rewrite)
    hits: list[dict]           # retrieved chunks
    context: str               # context used for generation
    citations: list[dict]      # citation sources
    answer: str                # final answer
    rewrite_count: int         # number of rewrites performed
    generate_count: int        # number of generations performed
    strict: bool               # strict-regeneration flag after a failed hallucination check
    grounded: bool             # hallucination-check result
    used_llm: bool             # whether this round's answer was generated by the LLM


# ---------------- utility functions ----------------
def _parse_json(text: str):
    """Extract JSON from LLM output (tolerates ```json fences and surrounding noise)."""
    text = text.strip()
    m = re.search(r"```(?:json)?\s*([\s\S]*?)```", text)
    if m:
        text = m.group(1).strip()
    m = re.search(r"[\[{][\s\S]*[\]}]", text)
    if m:
        text = m.group(0)
    return json.loads(text)


def build_context(hits: list[dict]) -> tuple[str, list[dict]]:
    """Organize retrieved chunks into numbered context and extract a deduplicated citation list."""
    parts: list[str] = []
    citations: list[dict] = []
    seen: set[int] = set()
    for i, h in enumerate(hits, 1):
        title = h.get("doc_title", "")
        page = int(h.get("source_page", 1) or 1)
        content = h.get("content", "") or ""
        parts.append(f"[{i}] \"{title}\", page {page}:\n{content}")
        did = int(h.get("doc_id", 0) or 0)
        if did not in seen:
            seen.add(did)
            citations.append(
                {"docId": did, "title": title, "page": page, "snippet": content[:120]}
            )
    return "\n\n".join(parts), citations


def fallback_answer(query: str, hits: list[dict]) -> str:
    """Retrieval-summary-style answer used when no LLM is configured."""
    if hits:
        lines = ["Based on the relevant content retrieved from the knowledge base, here is a summary:\n"]
        for i, h in enumerate(hits[:3], 1):
            snippet = (h.get("content", "") or "")[:140].strip()
            lines.append(f"{i}. {snippet} …")
        lines.append(
            "\n(Note: No LLM API key is currently configured; the above is a summary of retrieved snippets. Configure one for a more complete, intelligent answer.)"
        )
        return "\n".join(lines)
    return (
        f"No content related to \"{query}\" was found in the knowledge base.\n\n"
        "Please try rephrasing your question, or confirm that the relevant documents have been uploaded and indexed."
    )


def _hit_key(h: dict) -> tuple:
    return (
        int(h.get("doc_id", 0) or 0),
        int(h.get("source_page", 0) or 0),
        (h.get("content", "") or "")[:80],
    )


# ---------------- graph nodes ----------------
def plan_node(state: RagState) -> dict:
    """Routing + multi-hop decomposition: a single LLM call both selects target knowledge bases and splits sub-queries."""
    writer = get_stream_writer()
    query = state["original_query"]
    kb_ids = state.get("kb_ids") or []
    catalog = state.get("kb_catalog") or []

    routed_ids = list(kb_ids)
    sub_queries = [query]

    if llm.llm_available() and len(catalog) > 1:
        kb_lines = "\n".join(
            f"- id={k['id']} name: {k['name']} ({k.get('description') or 'no description'})"
            for k in catalog
        )
        prompt = (
            "You are an enterprise knowledge-base retrieval planning assistant. Based on the knowledge-base list and the user question, output JSON: "
            '{"kb_ids": [ids of knowledge bases relevant to the question], "sub_queries": ["retrieval sub-queries"]}.\n'
            "Rules:\n"
            "1. Keep in kb_ids only the knowledge bases clearly relevant to the question; when unsure, keep all candidates.\n"
            "2. If the question involves multiple independent aspects (e.g. asking about reimbursement and time-off at once), split it into 2-3 sub-queries; "
            "otherwise sub_queries contains only the original question.\n"
            "3. Output only JSON, with no explanation.\n\n"
            f"[Knowledge Base List]\n{kb_lines}\n\n[User Question]\n{query}"
        )
        try:
            data = _parse_json(llm.chat_once([{"role": "user", "content": prompt}]))
            picked = [int(x) for x in data.get("kb_ids", []) if int(x) in kb_ids]
            if picked:
                routed_ids = picked
            subs = [str(s).strip() for s in data.get("sub_queries", []) if str(s).strip()]
            if subs:
                sub_queries = subs[:3]
        except Exception:  # noqa: BLE001
            logger.warning("Retrieval planning failed; using all candidates", exc_info=True)

    name_map = {k["id"]: k["name"] for k in catalog}
    routed_kbs = [
        {"id": kid, "name": name_map.get(kid, "")} for kid in routed_ids[:3]
    ]
    writer({"type": "routing", "kbs": routed_kbs})
    return {
        "routed_kb_ids": routed_ids,
        "routed_kbs": routed_kbs,
        "sub_queries": sub_queries,
        "rewrite_count": 0,
        "generate_count": 0,
        "strict": False,
    }


def retrieve_node(state: RagState) -> dict:
    """Run hybrid search for each sub-query, then merge and dedupe; fall back to all candidates when the routed scope yields no hits."""
    writer = get_stream_writer()
    writer({"type": "retrieving"})

    kb_ids = state.get("kb_ids") or []
    routed_ids = state.get("routed_kb_ids") or kb_ids
    sub_queries = state.get("sub_queries") or [state["original_query"]]

    if not kb_ids or not es_client.is_available():
        return {"hits": []}

    per_k = 6 if len(sub_queries) == 1 else 4

    def _search(ids: list[int]) -> list[dict]:
        merged: list[dict] = []
        seen: set[tuple] = set()
        for q in sub_queries:
            try:
                rows = es_client.hybrid_search(
                    q, embed_text(q), kb_ids=ids, allowed_tags=None, top_k=per_k
                )
            except Exception:  # noqa: BLE001
                logger.warning("Hybrid search failed: %s", q, exc_info=True)
                rows = []
            for h in rows:
                key = _hit_key(h)
                if key not in seen:
                    seen.add(key)
                    merged.append(h)
        return merged[:8]

    hits = _search(routed_ids)
    # When overly narrow routing yields zero hits, broaden to all candidates as a fallback
    if not hits and set(routed_ids) != set(kb_ids):
        hits = _search(kb_ids)
    return {"hits": hits}


def grade_node(state: RagState) -> dict:
    """Retrieval quality assessment: filter out irrelevant chunks and provide a rewrite basis for the conditional edge."""
    hits = state.get("hits") or []
    if not llm.llm_available() or not hits:
        return {}

    writer = get_stream_writer()
    writer({"type": "stage", "stage": "grading"})

    numbered = "\n\n".join(
        f"[{i}] {(h.get('content', '') or '')[:300]}" for i, h in enumerate(hits, 1)
    )
    prompt = (
        "You are a retrieval-quality assessment assistant. Decide whether each snippet below helps answer the user question, "
        'and output JSON: {"relevant": [numbers of helpful snippets]}. Output only JSON.\n\n'
        f"[User Question]\n{state['original_query']}\n\n[Candidate Snippets]\n{numbered}"
    )
    try:
        data = _parse_json(llm.chat_once([{"role": "user", "content": prompt}]))
        idx = {int(i) for i in data.get("relevant", [])}
        filtered = [h for i, h in enumerate(hits, 1) if i in idx]
    except Exception:  # noqa: BLE001
        logger.warning("Retrieval assessment failed; keeping all hits", exc_info=True)
        return {}

    # When everything is judged irrelevant and no rewrite budget remains, keep the original hits as a fallback (the generation prompt decides what to use)
    if not filtered and state.get("rewrite_count", 0) >= MAX_REWRITES:
        return {}
    return {"hits": filtered}


def grade_route(state: RagState) -> str:
    """Enter rewrite when relevant chunks are insufficient and rewrite budget remains; otherwise generate directly."""
    if not llm.llm_available():
        return "generate"
    if len(state.get("hits") or []) >= 2:
        return "generate"
    if state.get("rewrite_count", 0) < MAX_REWRITES:
        return "rewrite"
    return "generate"


def rewrite_node(state: RagState) -> dict:
    """When retrieval performs poorly, rewrite the query and search again."""
    writer = get_stream_writer()
    writer({"type": "stage", "stage": "rewriting"})

    tried = "; ".join(state.get("sub_queries") or [])
    prompt = (
        "You are a query-rewriting assistant. The following question retrieves poorly in the enterprise knowledge base. "
        "Rewrite it into a query better suited for full-text and vector retrieval: keep key entities, replace colloquial phrasing with standard terminology, "
        "and add synonyms where appropriate. Output only the single rewritten query text.\n\n"
        f"[Original Question] {state['original_query']}\n[Queries Already Tried] {tried}"
    )
    new_query = state["original_query"]
    try:
        text = llm.chat_once([{"role": "user", "content": prompt}], max_tokens=128)
        if text:
            new_query = text.splitlines()[0].strip()
    except Exception:  # noqa: BLE001
        logger.warning("Query rewrite failed; keeping the original question", exc_info=True)
    return {
        "sub_queries": [new_query],
        "rewrite_count": state.get("rewrite_count", 0) + 1,
    }


def generate_node(state: RagState) -> dict:
    """Assemble context and stream the answer; strict mode appends a strict-grounding constraint."""
    writer = get_stream_writer()
    hits = state.get("hits") or []
    context, citations = build_context(hits)

    writer({"type": "generating"})

    answer = ""
    used_llm = False
    if llm.llm_available():
        try:
            messages = llm.build_messages(
                state["original_query"], context, state.get("history")
            )
            if state.get("strict"):
                messages[0]["content"] += (
                    "\nNote: the previous answer contained insufficiently grounded content. This time you must answer strictly using only "
                    "information that explicitly appears in the [Context]. For anything the context does not cover, state directly that it was not found; "
                    "do not speculate or add outside knowledge."
                )
            for delta in llm.stream_chat(messages):
                answer += delta
                writer({"type": "token", "delta": delta})
            used_llm = True
        except Exception:  # noqa: BLE001
            logger.warning("LLM call failed; falling back to summary", exc_info=True)
            answer = ""
    if not used_llm:
        answer = fallback_answer(state["original_query"], hits)
        for i in range(0, len(answer), 4):
            writer({"type": "token", "delta": answer[i : i + 4]})

    return {
        "answer": answer,
        "context": context,
        "citations": citations,
        "used_llm": used_llm,
        "generate_count": state.get("generate_count", 0) + 1,
    }


def verify_node(state: RagState) -> dict:
    """Hallucination check: when the answer is not faithful to the context and regeneration budget remains, enable strict mode and loop back."""
    if (
        not state.get("used_llm")
        or not state.get("context")
        or not state.get("answer")
        or state.get("generate_count", 0) >= MAX_GENERATES
    ):
        return {"grounded": True}

    writer = get_stream_writer()
    writer({"type": "stage", "stage": "verifying"})

    prompt = (
        "You are an answer-review assistant. Decide whether all key facts in the [Answer] can be supported by the [Context] "
        "(reasonable summarization and formatting are allowed; an answer that truthfully states 'no relevant content found' also passes). "
        'Output JSON: {"grounded": true/false}. Output only JSON.\n\n'
        f"[Context]\n{state['context'][:3000]}\n\n"
        f"[Question]\n{state['original_query']}\n\n[Answer]\n{state['answer'][:2000]}"
    )
    try:
        data = _parse_json(llm.chat_once([{"role": "user", "content": prompt}]))
        grounded = bool(data.get("grounded", True))
    except Exception:  # noqa: BLE001
        logger.warning("Hallucination check failed; allowing by default", exc_info=True)
        return {"grounded": True}

    if grounded:
        return {"grounded": True}
    # Failed: notify the frontend to clear the buffer and regenerate in strict mode
    writer({"type": "restart"})
    writer({"type": "stage", "stage": "regenerating"})
    return {"grounded": False, "strict": True}


def verify_route(state: RagState) -> str:
    return END if state.get("grounded", True) else "generate"


# ---------------- graph construction ----------------
def _build_graph():
    g = StateGraph(RagState)
    g.add_node("plan", plan_node)
    g.add_node("retrieve", retrieve_node)
    g.add_node("grade", grade_node)
    g.add_node("rewrite", rewrite_node)
    g.add_node("generate", generate_node)
    g.add_node("verify", verify_node)

    g.add_edge(START, "plan")
    g.add_edge("plan", "retrieve")
    g.add_edge("retrieve", "grade")
    g.add_conditional_edges(
        "grade", grade_route, {"generate": "generate", "rewrite": "rewrite"}
    )
    g.add_edge("rewrite", "retrieve")
    g.add_edge("generate", "verify")
    g.add_conditional_edges(
        "verify", verify_route, {"generate": "generate", END: END}
    )
    return g.compile()


rag_flow = _build_graph()
